#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
[ "${update_loc}" = "RUS" ] && export BN_LOC=ruRU || export BN_LOC=enUS
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/Battle.net-Setup-${BN_LOC}.exe"
start_portproton
if try_download "dist.blizzard.com/downloads/bna-installers/322d5bb9ae0318de3d4cde7641c96425/retail.1/Battle.net-Setup-${BN_LOC}.exe" "${PP_AUTOINSTALL_EXE}"
then
    # PP_START_PROGRESS_BAR "${loc_gui_installing_the} Battle Net. ${loc_gui_please_wait} "
    PP_kill_autostart Battle.net.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe=`find "$WINEPREFIX/drive_c/" -type f -name "Battle.net.exe"`
    PP_stop_progress_bar
    portwine_create_shortcut
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
fi
stop_portwine
