#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/BethesdaNetLauncher_Setup.exe"
start_portproton
if try_download "download.cdp.bethesda.net/BethesdaNetLauncher_Setup.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} BethesdaNetLauncher. ${loc_gui_please_wait} "
    PP_kill_autostart BethesdaNetLauncher.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="$WINEPREFIX/drive_c/Program Files (x86)/Bethesda.net Launcher/BethesdaNetLauncher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Bethesda.net"
    portwine_create_shortcut
fi
stop_portwine
