#!/usr/bin/env bash
# Author: Castro Fidel
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/crossout.exe"
# export PP_PREFIX_NAME=DOTNET

start_portproton
if try_download "https://yupmaster.gaijinent.com/launcher/current.php?id=CrossoutLauncher" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Crossout. ${loc_gui_please_wait} "
    PP_kill_autostart launcher.exe 3 &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="${WINEPREFIX}/drive_c/users/$USER/AppData/Local/Crossout/launcher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Crossout"
    portwine_create_shortcut
fi
stop_portwine
