#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/fulqrumgames_setup.exe"
start_portproton
if try_download "https://royalquest.com/download/fulqrum" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Fulqrum Games. ${loc_gui_please_wait} "
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="$WINEPREFIX/drive_c/FulqrumGames/FulqrumGames.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Fulqrum Games"
    portwine_create_shortcut
fi
stop_portwine
