#!/usr/bin/env bash
# Author: Castro Fidel
########################################################################
export LAUNCH_PARAMETERS=("/S")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/igclient_setup.exe"

start_portproton
if try_download "https://content.indiegalacdn.com/common/IGClientSetup.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Indiegala Client. ${loc_gui_please_wait} "
    PP_kill_autostart IGClient.exe 3 &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="${WINEPREFIX}/drive_c/Program Files/IGClient/IGClient.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="IGClient"
    portwine_create_shortcut
fi
stop_portwine
