#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export PP_PREFIX_NAME="LEAGUE_OF_LEGENDS"
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/live.na.exe"
export LAUNCH_PARAMETERS="--launch-product=league_of_legends --launch-patchline=live"
export PP_MUST_HAVE_DLL=""
export PP_VULKAN_USE=1
export PP_WINE_USE=WINE_LOL_GE_7.0-8
export WINEDLLOVERRIDES="mscoree,mshtml="
export PP_USE_D3D_EXTRAS=1

gui_proton_downloader silent "${PP_WINE_USE}"

start_portproton
if try_download "lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.na.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "Installing League of Legends. ${loc_gui_please_wait} "
    zenity --info --width=500 --text "You must click the install button without changing the settings!"   
    PP_kill_autostart RiotClientServices.exe &
    pp_run "${PP_AUTOINSTALL_EXE}" 
    portproton_exe="$WINEPREFIX/drive_c/Riot Games/Riot Client/RiotClientServices.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="League of Legend"
    portwine_create_shortcut
fi
stop_portwine
