#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/silent" "/NoLaunch" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/OriginSetup.exe"
start_portproton
if try_download "origin-a.akamaihd.net/Origin-Client-Download/origin/live/OriginThinSetup.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Origin. ${loc_gui_please_wait}"
    # PP_kill_autostart Origin.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="$WINEPREFIX/drive_c/Program Files (x86)/Origin/Origin.exe"
    PP_stop_progress_bar
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    portwine_create_shortcut
fi
stop_portwine 
