#!/usr/bin/env bash
# Author: cefeiko
########################################################################
export PP_PREFIX_NAME=DOTNET
start_portproton
export PP_DLL_INSTALL="dotnet48"
mkdir -p "${WINEPREFIX}/drive_c/Program Files (x86)/OSU/"
export PP_AUTOINSTALL_EXE="${WINEPREFIX}/drive_c/Program Files (x86)/OSU/osu!.exe"
if try_download "m1.ppy.sh/r/osu!install.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} OSU!. ${loc_gui_please_wait} "
    if  [ -f "${PORT_PROTON_PATH}/data/pfx_dotnet/drive_c/Program Files (x86)/OSU/osu!install.exe" ]; then
        mv -f  "${PORT_PROTON_PATH}/data/pfx_dotnet/drive_c/Program Files (x86)/OSU/osu!install.exe" "${PORT_PROTON_PATH}/data/pfx_dotnet/drive_c/Program Files (x86)/OSU/osu!.exe"
    fi
    portproton_exe="$WINEPREFIX/drive_c/Program Files (x86)/OSU/osu!.exe"
    try_remove_file "${portproton_exe}.ppdb"
    # pp_run "${PP_AUTOINSTALL_EXE}"
    PP_stop_progress_bar
    portwine_create_shortcut
    kill_portwine
fi
stop_portwine
