#!/usr/bin/env bash
# Author: chal55rus
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PP_WINDOWS_VER="7"
export PP_PREFIX_NAME="PANZAR"
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/Panzar.exe"

start_portproton
if try_download "https://www.panzar.ru/ru/download/installer/" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Panzar. ${loc_gui_please_wait} "
    PP_kill_autostart start.exe 3 &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="${WINEPREFIX}/drive_c/Games/Panzar/PnzSteamLauncher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Panzar"
    portwine_create_shortcut
fi
stop_portwine
