#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/Setup Project64 3.0.1-5664-2df3434.exe"
start_portproton
if try_download "www.pj64-emu.com/file/setup-project64-3-0-0-5632-f83bee9/" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Project64. ${loc_gui_please_wait} "
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="$WINEPREFIX/drive_c/Program Files (x86)/Project64 3.0/Project64.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Project64"
    portwine_create_shortcut
fi
stop_portwine
