#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/duckstation-windows-x64-release.zip"
start_portwine
if try_download "github.com/stenzek/duckstation/releases/download/preview/duckstation-windows-x64-release.zip" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} VBA-M. ${loc_gui_please_wait} "
    "$PP_7z" x -y "${PP_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/Duckstation"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Duckstation/duckstation-qt-x64-ReleaseLTCG.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="DuckStation"
    portwine_create_shortcut
fi
stop_portwine
