#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/silent" "/repair" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/EAappInstaller.exe"
export PP_DLL_INSTALL=""               # Install DDL in port prefix (used winetricks) 
export PP_VULKAN_USE=1
export PP_MUST_HAVE_DLL=""
export PP_PREFIX_NAME="EA_APP"
# export WINEDLLOVERRIDES="mscoree,mshtml=b"
# export PP_WINE_USE="WINE-8.2-STAGING-TKG-AMD64"
# gui_proton_downloader silent "WINE-8.2-STAGING-TKG-AMD64"

start_portwine
if try_download "origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} EA Launcher. ${loc_gui_please_wait} "
    # PP_kill_autostart EABackgroundService.exe &
    # PP_kill_autostart EALocalHostSvc.exe &
    mkdir -p "$WINEPREFIX/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop"
    PP_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe"
    PP_stop_progress_bar
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    portwine_create_shortcut
fi
stop_portwine 
