#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################## 
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/PPSSPPSetup.exe"
start_portwine
if try_download "www.ppsspp.org/files/1_12_3/PPSSPPSetup.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} PPSSPPS. ${loc_gui_please_wait} "
    PP_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files/PPSSPP/PPSSPPWindows64.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="PPSSPPWindows"
    portwine_create_shortcut
fi
stop_portwine
