#!/usr/bin/env bash
# Author: Castro Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/S")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/PathOfExileInstaller.exe"
export PP_PREFIX_NAME="PATH_OF_EXILE"

start_portwine
if try_download "https://web.poecdn.com/protected/downloads/PathOfExileInstaller.exe?key=lpKVe-ZJOqVrur8612s8gg" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Path of Exile. ${loc_gui_please_wait}"
    PP_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Grinding Gear Games/Path of Exile/PathOfExile.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Path of Exile"
    portwine_create_shortcut
fi
stop_portwine
