#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PP_PREFIX_NAME=DOTNET
export LAUNCH_PARAMETERS=("/s" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/plarium_play_setup.exe"
start_portwine
if try_download "https://plarium.com/services/api/downloads/desktop?lid=1&arc=64&os=windows" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Plarium Play. ${loc_gui_please_wait}"
    PP_kill_autostart PlariumPlay.exe &
    PP_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/PlariumPlay/PlariumPlay.exe" 
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Plarium Play"
    portwine_create_shortcut
fi
stop_portwine
