#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/S" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/EXBO_Setup_ru.exe"
export PP_PREFIX_NAME=DOTNET


start_portwine
if try_download "exbo2.b-cdn.net/EXBO_Setup_ru.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "Installing STALCRAFT Launcher. ${loc_gui_please_wait} "
    PP_kill_autostart ExboLauncher &
    PP_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Roaming/EXBO/java/bin/ExboLauncher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="STALCRAFT"
    portwine_create_shortcut
fi
stop_portwine
