#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################## 
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/scummvm-2.5.0-win32.exe"
start_portwine
if try_download "downloads.scummvm.org/frs/scummvm/2.5.0/scummvm-2.5.0-win32.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} ScummVM. ${loc_gui_please_wait} "
    #PP_kill_autostart launcher101xp.exe &
    PP_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files/ScummVM/scummvm.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="ScummVM"
    portwine_create_shortcut
fi
stop_portwine


#/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-

#downloads.scummvm.org/frs/scummvm/2.5.0/scummvm-2.5.0-win32.exe
