#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/S" "/D=c:\Program Files (x86)\Ubisoft Game Launcher")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/UbisoftConnectInstaller.exe"
start_portwine
if try_download "ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_cs "${loc_gui_installing_the} Ubisoft Connect. ${loc_gui_please_wait} "
    PP_kill_autostart UbisoftConnect.exe &
    PP_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Ubisoft Game Launcher/UbisoftConnect.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
