#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("")
export PP_PREFIX_NAME="VK_PLAY"
export PP_AUTOINSTALL_EXE="${PORT_PROTON_PATH}/data/prefixes/${PP_PREFIX_NAME}/drive_c/users/steamuser/AppData/Local/VKPlayLoader.exe"
export WINEDLLOVERRIDES="mscoree,mshtml="
export PP_MUST_HAVE_DLL=""

start_portwine
if try_download "static.gc.my.games/VKPlayLoader.exe" "${PP_AUTOINSTALL_EXE}"
then
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/VKPlayLoader.exe"
    try_remove_file "${portwine_exe}.ppdb"
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="vkPlay"
    portwine_create_shortcut
fi
stop_portwine
