#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("")
export PP_PREFIX_NAME="ROBLOX"
export PP_AUTOINSTALL_EXE="${PORT_PROTON_PATH}/data/prefixes/${PP_PREFIX_NAME}/drive_c/roblox_installer.exe"
export WINEDLLOVERRIDES="mscoree,mshtml="
export PP_MUST_HAVE_DLL=""
export PP_WINE_USE="WINE-8.2-STAGING-TKG-AMD64"

gui_proton_downloader silent "WINE-8.2-STAGING-TKG-AMD64"

start_portproton
if try_download "setup.rbxcdn.com/RobloxPlayerLauncher.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_run "${PP_AUTOINSTALL_EXE}"
    portproton_exe="${WINEPREFIX}/drive_c/users/${USER}/AppData/Local/Roblox/Versions/version-5e9aac577efb4995/RobloxPlayerBeta.exe"
    try_remove_file "${portproton_exe}.ppdb"
    PP_stop_progress_bar
    # export PORTWINE_CREATE_SHORTCUT_NAME="RobloxPlayerBeta"
    portwine_create_shortcut
fi
stop_portwine
