#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/Rockstar-Games-Launcher.exe"
start_portproton
if try_download "web.archive.org/web/20210708074247if_/gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "Rockstar-Games-Launcher. ${loc_gui_please_wait} "
    "$PP_7z" x -y "${PP_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher"
    portproton_exe="$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher/Launcher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Rockstar"
    portwine_create_shortcut
fi
stop_portwine
