#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/S" "/D=c:\Program Files (x86)\Steam")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/SteamSetup.exe"
start_portproton
if try_download "cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_cs "${loc_gui_installing_the} Steam. ${loc_gui_please_wait} "
    PP_kill_autostart steam.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    if [ -f "$WINEPREFIX/drive_c/Program Files (x86)/Steam/Steam.exe" ]
    then mv -f "$WINEPREFIX/drive_c/Program Files (x86)/Steam/Steam.exe" "$WINEPREFIX/drive_c/Program Files (x86)/Steam/steam.exe"
    fi
    portproton_exe="$WINEPREFIX/drive_c/Program Files (x86)/Steam/steam.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="STEAM_PP"
    portwine_create_shortcut
fi
stop_portwine
