#!/usr/bin/env bash
# Author: chal55rus
########################################################################
export PP_PREFIX_NAME="SWL"
export WINEDLLOVERRIDES="d3d9=b"
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/SecretWorldLegendsMin.exe"

start_portproton
if try_download "https://web-cdn.funcom.com/downloads/swl/SecretWorldLegendsMin.exe" "${PP_AUTOINSTALL_EXE}"
then
    PP_start_progress_bar_block "${loc_gui_installing_the} Secret World Legends. ${loc_gui_please_wait} "
    PP_kill_autostart ClientPatcher.exe &
#    PP_kill_autostart PatcherSetup.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
#    portproton_exe="${WINEPREFIX}/drive_c/Program Files (x86)/Funcom/Secret World Legends/SecretWorldLegendsDX11.exe"
    portproton_exe="${WINEPREFIX}/drive_c/Program Files (x86)/Funcom/Secret World Legends/ClientPatcher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    try_remove_file "${portproton_exe}.ppdb"
    kill_portwine
    PP_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Secret World Legends"
    portwine_create_shortcut
fi
stop_portwine
