#!/usr/bin/env bash
#Author: PortWINE
#EALauncher.exe
#EADesktop.exe
#Rating=5
#####################examples###########################
# export PP_DLL_INSTALL="vcrun2022"               # Install DDL in port prefix (used winetricks) 
export PP_VULKAN_USE=1                       # dxvk, vkd3d or 0 for OpenGL
# export PP_USE_TERMINAL="1"
export PP_MUST_HAVE_DLL=""
export PP_PREFIX_NAME="EA_APP"
# export PP_WINE_USE="WINE-8.2-STAGING-TKG-AMD64"
# gui_proton_downloader silent "WINE-8.2-STAGING-TKG-AMD64"
