#!/usr/bin/env bash
#Author: castro-fidel
#PnzSteamLauncher.exe
#Rating=1-5
#####################examples###########################
##export PP_COMMENT_DB="blablabla"
export PP_WINDOWS_VER="7"
export PP_DLL_INSTALL=""
export WINEDLLOVERRIDES=""
export LAUNCH_PARAMETERS=""
export PP_VULKAN_USE="1"
export PP_USE_DXR10="0"
##export PP_DLSS_ON=1
##export PP_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
export PP_USE_NVAPI_AND_DLSS="0"
export PP_OLD_GL_STRING="0"
export PP_HIDE_NVIDIA_GPU="0"
##export PP_FORCE_USE_VSYNC=0                     # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
export PP_VIRTUAL_DESKTOP="0"
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export ENABLE_VKBASALT="1"
export PP_VKBASALT_EFFECTS="Curves:cas"
export PP_VKBASALT_FFX_CAS="0.75"
export PP_NO_FSYNC="0"
export PP_NO_ESYNC="1"
export PP_USE_TERMINAL="0"
export PP_GUI_DISABLED_CS="0"
##export PATH_TO_GAME=
##add_in_start_portwine () { commands ; }
export PP_PREFIX_NAME="PANZAR"
export PP_USE_DXR11="0"
export PP_USE_FAKE_DLSS="0"
export PP_WINE_FULLSCREEN_FSR="1"
export PP_USE_GAMEMODE="1"
export PP_DX12_DISABLE="0"
export PP_PRIME_RENDER_OFFLOAD="0"
export PP_USE_D3D_EXTRAS="1"
export PP_FIX_VIDEO_IN_GAME="0"
export PP_FORCE_LARGE_ADDRESS_AWARE="1"
export PP_USE_SHADER_CACHE="0"
export PP_USE_WINE_DXGI="0"
