#!/usr/bin/env bash
#Author: Castro-Fidel
#SecretWorldLegendsDX11.exe
#ClientPatcher.exe
#Rating=1-5
#####################examples###########################
##export PP_COMMENT_DB="blablabla"
export PP_PREFIX_NAME="SWL"
export WINEDLLOVERRIDES="d3d9=b"
export ENABLE_VKBASALT="1"
export PP_VKBASALT_EFFECTS="Curves:cas"
export PP_VKBASALT_FFX_CAS="0.75"
