#!/usr/bin/env bash
#Author: linux-gaming.ru
#setup.exe
#Setup.exe
#SETUP.exe
#.msi
#Rating=5
#export PP_COMMENT_DB="blablabla"
################################################
export PP_DISABLED_CREATE_DB=1
export PP_ICON_FOR_YAD="${PORT_PROTON_PATH}/data/img/setup.png" 
export PP_VULKAN_USE=1
export PP_MANGOHUD=0
export PP_NO_FSYNC=1        # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
export PP_NO_ESYNC=1        # Do not use eventfd-based in-process synchronization primitives
export PP_WINEDBG_DISABLE=1
export PP_USE_GAMEMODE=0             # Force disabele gamemod
export PP_FORCE_LARGE_ADDRESS_AWARE=1          # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
export PP_DLL_INSTALL=""

add_in_stop_portwine () {
    PP_find_exe news
}
