#!/usr/bin/env bash
#Author: linux-gaming.ru
#steam.exe
#Rating=5
################################################
export PP_COMMENT_DB="Steam"
export PP_WINDOWS_VER="10"
export PP_DLL_INSTALL="vcrun2022 d3dcompiler_46"
export WINEDLLOVERRIDES=""
export LAUNCH_PARAMETERS="-gamepadui -fullscreen -no-dwrite"
export PP_VULKAN_USE="1"

add_in_start_portproton () {
    echo "Disabled silent autostart steam."
    if [[ -f "${PORT_PROTON_PATH}/data/prefixes/${PP_PREFIX_NAME}/user.reg" ]] ; then
        sed -i '/steam.exe\\" -silent"/d' "${PORT_PROTON_PATH}/data/prefixes/${PP_PREFIX_NAME}/user.reg"
    fi
}
