#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
# Development assistants:
########################################################################
echo '
            █░░ █ █▄░█ █░█ ▀▄▀ ▄▄ █▀▀ ▄▀█ █▀▄▀█ █ █▄░█ █▀▀ ░ █▀█ █░█
            █▄▄ █ █░▀█ █▄█ █░█ ░░ █▄█ █▀█ █░▀░█ █ █░▀█ █▄█ ▄ █▀▄ █▄█

██████╗░░█████╗░██████╗░████████╗██████╗░██████╗░░█████╗░████████╗░█████╗░███╗░░██╗
██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗██╔══██╗╚══██╔══╝██╔══██╗████╗░██║
██████╔╝██║░░██║██████╔╝░░░██║░░░██████╔╝██████╔╝██║░░██║░░░██║░░░██║░░██║██╔██╗██║
██╔═══╝░██║░░██║██╔══██╗░░░██║░░░██╔═══╝░██╔══██╗██║░░██║░░░██║░░░██║░░██║██║╚████║
██║░░░░░╚█████╔╝██║░░██║░░░██║░░░██║░░░░░██║░░██║╚█████╔╝░░░██║░░░╚█████╔╝██║░╚███║
╚═╝░░░░░░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░░╚════╝░╚═╝░░╚══╝

'
# set -x
# запрещаем запуск от root
if [[ $(id -u) = 0 ]] ; then
    echo "Запускать всё подряд от root вредно для системы!"
    exit 1
fi
# переходим в каталог с PortProton
cd "$(dirname "`readlink -f "$0"`")/../../" 
# создаем переменную с путем до PortProton
export PORT_PROTON_PATH="$(pwd)"
# создаем переменную с путем до PortProton
export PORT_PROTON_DATA_PATH="${PORT_PROTON_PATH}/data"
# создаем переменную с путем до скриптов
export PORT_PROTON_SCRIPTS_PATH="${PORT_PROTON_DATA_PATH}/scripts"
# переходим в каталог scripts
cd "${PORT_PROTON_SCRIPTS_PATH}"

# подключаем скрипт с переменными из var
. "${PORT_PROTON_SCRIPTS_PATH}/var"

# проверяем существует ли скрипт user.conf и подключаем его
export USER_CONF="${PORT_PROTON_DATA_PATH}/user.conf"
if [ ! -f "${USER_CONF}" ]; then
    echo "#!/usr/bin/env bash" > "${USER_CONF}"
    echo "# User overides db and var settings..." >> "${USER_CONF}"
    chmod u+x "${USER_CONF}"
fi
. "${USER_CONF}"

# подключаем скрипт с доп. функциями
. "${PORT_PROTON_SCRIPTS_PATH}/functions_helper"

# создаем необходимые каталоги
create_new_dir "${PORT_PROTON_DATA_PATH}/tmp"
create_new_dir "${PORT_PROTON_DATA_PATH}/dist"
create_new_dir "${PORT_PROTON_DATA_PATH}/prefixes"
create_new_dir "${PORT_PROTON_DATA_PATH}/prefixes/DEFAULT"
create_new_dir "${PORT_PROTON_DATA_PATH}/prefixes/DOTNET"

# создаем симлинк каталога prefixes в основной каталог PortProton
try_force_link_dir "${PORT_PROTON_PATH}/data/prefixes" "${PORT_PROTON_PATH}"

# парсим каталоги где есть разные версии wine и записываем вывод в файлы wine_* в каталоге tmp
parsing_dir "${PORT_PROTON_PATH}/data/dist" "${PORT_PROTON_DATA_PATH}/tmp/wine_portproton.tmp" 
parsing_dir "/home/${USER}/.local/share/Steam/steamapps/common/" "${PORT_PROTON_DATA_PATH}/tmp/wine_steam.tmp" proton # !!! добавить в конец пути /file/
sed -i '/Runtime/d' "${PORT_PROTON_DATA_PATH}/tmp/wine_steam.tmp" # удаляем лишнее из wine_steam.tmp
parsing_dir "/home/${USER}/.local/share/lutris/runners/wine/" "${PORT_PROTON_DATA_PATH}/tmp/wine_lutris.tmp" x86_64
parsing_dir "/home/${USER}/.PlayOnLinux/wine/linux-amd64/" "${PORT_PROTON_DATA_PATH}/tmp/wine_playonlinux.tmp"

echo "
Выводим список всех установленных версий WINE:"
cat "${PORT_PROTON_DATA_PATH}/tmp/wine_"*

# парсим каталог prefix и записываем вывод в файл prefixes.tmp в каталоге tmp
orig_IFS="$IFS"
IFS=$'\n'
try_remove_file "${PORT_PROTON_DATA_PATH}/tmp/prefixes.tmp"
for pfx_dir in $(ls -1 "${PORT_PROTON_PATH}/data/prefixes/") ; do
    pfx_dir_new=`echo "${pfx_dir}" | awk '$1=$1' | sed -e s/[[:blank:]]/_/g`
    if [[ ! -d "${PORT_PROTON_PATH}/data/prefixes/${pfx_dir_new^^}" ]] ; then
        mv -- "${PORT_PROTON_PATH}/data/prefixes/$pfx_dir" "${PORT_PROTON_PATH}/data/prefixes/${pfx_dir_new^^}"
    fi
    if [[ -d "${PORT_PROTON_DATA_PATH}/prefixes/${pfx_dir_new^^}" ]] ; then
        echo "${pfx_dir_new^^}=\"${PORT_PROTON_DATA_PATH}/prefixes/${pfx_dir_new^^}\"" >> "${PORT_PROTON_DATA_PATH}/tmp/prefixes.tmp"
    fi
done
IFS="$orig_IFS"
echo "
Выводим список всех префиксов существующих в PortProton:"
cat "${PORT_PROTON_DATA_PATH}/tmp/prefixes.tmp"

# парсим каталог portproton_autoinstall и записываем вывод в файл portproton_autoinstall.tmp в каталоге tmp
parsing_dir "${PORT_PROTON_SCRIPTS_PATH}/portproton_autoinstall" "${PORT_PROTON_DATA_PATH}/tmp/portproton_autoinstall.tmp"
sed -i '/.png/d' "${PORT_PROTON_DATA_PATH}/tmp/portproton_autoinstall.tmp" # удаляем иконки из списка в файле portproton_autoinstall.tmp
echo "
Выводим список всех скриптов автоматических установок игр/приложений:"
cat "${PORT_PROTON_DATA_PATH}/tmp/portproton_autoinstall.tmp"

echo "
END"
