#!/usr/bin/env bash
#Author: Castro-Fidel (linux-gaming.ru)
#SCRIPTS_NEXT_VERSION=0003
########################################################################
export PP_URL="https://linux-gaming.ru/portproton/"
export PP_MANGOHUD=0
export MANGOHUD_CONFIG=cpu_stats,cpu_temp,cpu_mhz,cpu_color=2e97cb,cpu_text=CPU,gpu_stats,gpu_temp,gpu_core_clock,gpu_mem_clock,vulkan_driver,gpu_name,gpu_color=2e9762,gpu_text=GPU,vram,vram_color=ad64c1,ram,ram_color=c26693,io_color=a491d3,frame_timing=1,frametime_color=00ff00,time,arch,wine,wine_color=eb5b5b,engine_color=eb5b5b,background_alpha=0.2,font_size=24,background_color=020202,text_color=ffffff,toggle_hud=Shift_R+F12,resolution,gamemode,vkbasalt
#export DXVK_HUD=compiler
#export GALLIUM_HUD=fps
#export ENABLE_VKBASALT=1
#export PP_VIRTUAL_DESKTOP=1
#export PP_XKBD_RU_HACK=1
export PP_NO_ESYNC="1"
export PP_USE_GAMEMODE="1"
export PP_FORCE_USE_VSYNC="2"
export PP_LOG="0"
export PP_USE_TERMINAL="0"
export PP_WINEDBG_DISABLE="1"
export PP_WINDOWS_VER="10"
export WINEARCH="win64"
export PP_LIBS_VER="_v42"
export GDK_BACKEND="x11"
export PP_USE_GSTREAMER="1"
export PP_USE_D3D_EXTRAS="1"
export PP_PREFIX_NAME="DEFAULT"
export WINE_WIN_START="start /i /b /wait /high /unix"
export PP_USE_SHADER_CACHE="1"
export STAGING_SHARED_MEMORY="1"
export PP_FORCE_LARGE_ADDRESS_AWARE="1"
# export VKD3D_FEATURE_LEVEL=12_0
export WINETRICKS_DOWNLOADER="curl"
###DEFAULT_WINE###
export PP_WINE_DEFAULT_USE="PROTON_LG_7-54"
export PP_PLUGINS_VER="_v10"
export PP_FAKE_DLSS_VER="091122"
export PP_WINE_FULLSCREEN_FSR="1"
###DXVK_AND_VKD3D###
export DXVK_STABLE_VER="1.10.3-28"
export DXVK_GIT_VER="2.1-51"
export VKD3D_STABLE_VER="1.1-2602"
export VKD3D_GIT_VER="1.1-3339"
###PREFIX_VERSION###
export DOTPFX_VER="48v1"
export DEFPFX_VER="v1"
#################################################################
export DXVK_CONFIG_FILE="${PORT_PROTON_PATH}/data/dxvk.conf"
#################################################################
export WINE_MONO_OVERRIDES="Microsoft.Xna.Framework.*,Gac=n"

PP_install_dll_in_prefix ()
{
    case $PP_PREFIX_NAME in
        DEFAULT) export PP_MUST_HAVE_DLL="physx mfc42 vcrun2022" ;;
         DOTNET) export PP_MUST_HAVE_DLL="physx mfc42 vcrun2022 faudio dotnet48" ;;
              *) export PP_MUST_HAVE_DLL="" ;;
    esac
}
########################################################################
add_in_start_portproton ()
{
    echo " "
}
########################################################################
add_in_stop_portwine ()
{
    echo " "
}
########################################################################
PP_other_fixes () 
{
    echo ""
}

